const CouponActionTypes = {
    CHECK_COUPON : "CHECK_COUPON",
	FETCH_COUPON_START: 'FETCH_COUPON_START',
    FETCH_COUPON_SUCCESS: 'FETCH_COUPON_SUCCESS',
    FETCH_COUPON_FAIL: 'FETCH_COUPON_FAIL'

};

export default CouponActionTypes;
